variables:
  CI_REGISTRY: docker.io
  IMAGE_FAMILY: stackstate/trafficmirror

stages:
  - build
  - docker_build

docker_build:
  stage: docker_build
  image: docker:stable
  script:
    - echo "${docker_password}" | docker login --username=${docker_user} --password-stdin ${CI_REGISTRY}
    - docker build
      --tag "${CI_REGISTRY}/${IMAGE_FAMILY}:${CI_BUILD_REF:-dirty}"
      --target app
      ${PWD}
    - docker push "${CI_REGISTRY}/${IMAGE_FAMILY}:${CI_BUILD_REF:-dirty}"
